name: recase_string_extension
version: 1.0.0
description: Applies recase to String, as an extension.
homepage: https://github.com/techniboogie-dart/recase_string_extension
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  recase: '^2.0.1'
dev_dependencies:
  test: '^1.0.0'
